🍎 Build JVips dependencies on MacOS
criteo/JVips pull request #129
Opened 2022-05-11 12:24 UTC by anthonyroussel

Hello

The goal of this pull-request to:
    
* Harmonise the build between the different architectures (linux, w64, macOS)
* Install only the build dependencies required to build Jvips
* Speed up the build of JVips on MacOS
* Trigger the MacOS build when a pull-request is created
* Upgrade libexif to 0.6.24

However, this has its drawbacks:
    
* `lib/CMakeLists.txt` has to be maintained for MacOS

2022-05-12 04:52 UTC, dbouron requested changes
Hi @anthonyroussel,

Thank you for this bunch of commits.

We can merge all commits except the one for building macos deps. I'd like to merge some [others dependencies](https://github.com/criteo/JVips/pull/125/commits) first.
Can you please split your PR?

> `lib/CMakeLists.txt` has to be maintained for MacOS
<img src="https://media.giphy.com/media/Xjo8pbrphfVuw/giphy.gif" width="256" />

2022-05-12 04:52 UTC, dbouron commented on .github/workflows/build.yml
> -    if: github.event_name != 'pull_request' # To speed up the feedback
In the past, the macos build took more than 30 min this is why we remove this jobs from PR event.
Last build took 16 min (~10 min for Linux) which is acceptable. So we can enable it back.

2022-05-12 04:52 UTC, dbouron commented on lib/VERSIONS
> +EXIF_VERSION=0.6.24
lgtm

2022-05-12 04:52 UTC, dbouron commented on lib/CMakeLists.txt
> +  set(CONFIGURE_CXXFLAGS "${CMAKE_CXX_FLAGS}")
Good catch :wrench:

2022-05-12 04:52 UTC, dbouron commented on .github/workflows/build.yml
> +      - name: Install build dependencies
I am pretty sure that it will be the root of all evil :apple:

2022-05-12 04:52 UTC, dbouron commented on lib/CMakeLists.txt
> +          -DENABLE_DOCS=0
Thank you for this contribution :slightly_smiling_face:

2022-05-12 04:52 UTC, dbouron commented on Toolchain-macOS.cmake
> +set(CMAKE_SYSTEM_PROCESSOR AMD64)
NIT: `set` in uppercase for style homogeneity please

2022-05-18 15:55 UTC, anthonyroussel commented
> Hi @anthonyroussel,
> 
> Thank you for this bunch of commits.
> 
> We can merge all commits except the one for building macos deps. I'd like to merge some [others dependencies](https://github.com/criteo/JVips/pull/125/commits) first. Can you please split your PR?
> 
> > `lib/CMakeLists.txt` has to be maintained for MacOS
> 
> <img alt="" width="256" src="https://camo.githubusercontent.com/90af01346a40389b3770c67824c526270b23a7b04e74d94cedaf35a8779d9662/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f586a6f387062727068665675772f67697068792e676966">

Hello,

Thanks for the review!

No problem, I removed the "Build JVips dependencies on MacOS" commit from this PR :)

2022-05-20 13:40 UTC, dbouron approved these changes

2022-05-20 14:49 UTC, dbouron commented
Hi @anthonyroussel,
Thank you for your previous changes. I rebased your other PR which produced some conflicts. Sorry about that.

2022-05-20 14:57 UTC, anthonyroussel commented
> Hi @anthonyroussel, Thank you for your previous changes. I rebased your other PR which produced some conflicts. Sorry about that.

Hello

No problem, I just resolved the conflicts :)

2022-05-20 16:24 UTC, merged